"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 18:01:48.844801
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


SCHEMAS = ("crm", "fsm", "erp", "agent")
SEQUENCES = (("crm", "ticket_id_seq"), ("fsm", "work_order_id_seq"), ("erp", "purchase_order_id_seq"))


def upgrade() -> None:
    for schema in SCHEMAS:
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
    for schema, name in SEQUENCES:
        op.execute(sa.schema.CreateSequence(sa.Sequence(name, schema=schema)))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("contract_tier", sa.String(length=10), nullable=False),
        sa.Column("contact_email", sa.String(length=200), nullable=False),
        sa.CheckConstraint("contract_tier IN ('gold', 'silver', 'bronze')", name="ck_customers_tier"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_email"),
        schema="crm",
    )
    op.create_table(
        "parts",
        sa.Column("sku", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("compatible_models", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("unit_cost_lkr", sa.Integer(), nullable=False),
        sa.Column("stock_qty", sa.Integer(), nullable=False),
        sa.Column("reorder_level", sa.Integer(), nullable=False),
        sa.CheckConstraint("stock_qty >= 0", name="ck_parts_stock_non_negative"),
        sa.PrimaryKeyConstraint("sku"),
        schema="erp",
    )
    op.create_table(
        "vendors",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="erp",
    )
    op.create_table(
        "fault_codes",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("symptoms", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("applies_to_models", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("likely_parts", postgresql.ARRAY(sa.String(length=30)), nullable=False),
        sa.Column("skill_required", sa.String(length=30), nullable=False),
        sa.Column("est_hours", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
        schema="fsm",
    )
    op.create_table(
        "technicians",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("skills", postgresql.ARRAY(sa.String(length=30)), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="fsm",
    )
    op.create_table(
        "vendor_parts",
        sa.Column("vendor_id", sa.String(length=20), nullable=False),
        sa.Column("sku", sa.String(length=30), nullable=False),
        sa.Column("price_lkr", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["erp.parts.sku"],
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["erp.vendors.id"],
        ),
        sa.PrimaryKeyConstraint("vendor_id", "sku"),
        schema="erp",
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("serial", sa.String(length=50), nullable=False),
        sa.Column("site", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("install_date", sa.Date(), nullable=False),
        sa.Column("warranty_end", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["crm.customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial"),
        schema="fsm",
    )
    op.create_index(op.f("ix_fsm_assets_customer_id"), "assets", ["customer_id"], unique=False, schema="fsm")
    op.create_table(
        "availability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("technician_id", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start", sa.Time(), nullable=False),
        sa.Column("end", sa.Time(), nullable=False),
        sa.Column("booked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["fsm.technicians.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("technician_id", "date", "start", name="uq_availability_slot"),
        schema="fsm",
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("customer_id", sa.String(length=20), nullable=False),
        sa.Column("asset_id", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("priority", sa.String(length=2), nullable=True),
        sa.Column("sla_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.CheckConstraint("priority IN ('P1', 'P2', 'P3')", name="ck_tickets_priority"),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["fsm.assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["crm.customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="crm",
    )
    op.create_table(
        "service_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("fault_code", sa.String(length=40), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("parts_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("technician_id", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["fsm.assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fault_code"],
            ["fsm.fault_codes.code"],
        ),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["fsm.technicians.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fsm",
    )
    op.create_index(
        op.f("ix_fsm_service_history_asset_id"), "service_history", ["asset_id"], unique=False, schema="fsm"
    )
    op.create_table(
        "ticket_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.String(length=20), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("direction IN ('inbound', 'outbound')", name="ck_ticket_messages_direction"),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["crm.tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="crm",
    )
    op.create_index(
        op.f("ix_crm_ticket_messages_ticket_id"), "ticket_messages", ["ticket_id"], unique=False, schema="crm"
    )
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("vendor_id", sa.String(length=20), nullable=False),
        sa.Column("ticket_id", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_lkr", sa.Integer(), nullable=False),
        sa.Column("warranty_claim", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft', 'pending_approval', 'approved', 'rejected', 'sent')",
            name="ck_purchase_orders_status",
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["crm.tickets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["erp.vendors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="erp",
    )
    op.create_index(
        op.f("ix_erp_purchase_orders_ticket_id"), "purchase_orders", ["ticket_id"], unique=False, schema="erp"
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=30), nullable=False),
        sa.Column("ticket_id", sa.String(length=20), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("qty > 0", name="ck_reservations_qty"),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["erp.parts.sku"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["crm.tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="erp",
    )
    op.create_index(
        op.f("ix_erp_reservations_ticket_id"), "reservations", ["ticket_id"], unique=False, schema="erp"
    )
    op.create_table(
        "work_orders",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("ticket_id", sa.String(length=20), nullable=False),
        sa.Column("asset_id", sa.String(length=20), nullable=False),
        sa.Column("technician_id", sa.String(length=20), nullable=False),
        sa.Column("scheduled_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("est_hours", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["fsm.assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technician_id"],
            ["fsm.technicians.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["crm.tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="fsm",
    )
    op.create_index(
        op.f("ix_fsm_work_orders_ticket_id"), "work_orders", ["ticket_id"], unique=False, schema="fsm"
    )
    op.create_table(
        "po_lines",
        sa.Column("po_id", sa.String(length=20), nullable=False),
        sa.Column("sku", sa.String(length=30), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_price_lkr", sa.Integer(), nullable=False),
        sa.CheckConstraint("qty > 0", name="ck_po_lines_qty"),
        sa.ForeignKeyConstraint(
            ["po_id"],
            ["erp.purchase_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["erp.parts.sku"],
        ),
        sa.PrimaryKeyConstraint("po_id", "sku"),
        schema="erp",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("po_lines", schema="erp")
    op.drop_index(op.f("ix_fsm_work_orders_ticket_id"), table_name="work_orders", schema="fsm")
    op.drop_table("work_orders", schema="fsm")
    op.drop_index(op.f("ix_erp_reservations_ticket_id"), table_name="reservations", schema="erp")
    op.drop_table("reservations", schema="erp")
    op.drop_index(op.f("ix_erp_purchase_orders_ticket_id"), table_name="purchase_orders", schema="erp")
    op.drop_table("purchase_orders", schema="erp")
    op.drop_index(op.f("ix_crm_ticket_messages_ticket_id"), table_name="ticket_messages", schema="crm")
    op.drop_table("ticket_messages", schema="crm")
    op.drop_index(op.f("ix_fsm_service_history_asset_id"), table_name="service_history", schema="fsm")
    op.drop_table("service_history", schema="fsm")
    op.drop_table("tickets", schema="crm")
    op.drop_table("availability", schema="fsm")
    op.drop_index(op.f("ix_fsm_assets_customer_id"), table_name="assets", schema="fsm")
    op.drop_table("assets", schema="fsm")
    op.drop_table("vendor_parts", schema="erp")
    op.drop_table("technicians", schema="fsm")
    op.drop_table("fault_codes", schema="fsm")
    op.drop_table("vendors", schema="erp")
    op.drop_table("parts", schema="erp")
    op.drop_table("customers", schema="crm")
    # ### end Alembic commands ###

    for schema, name in SEQUENCES:
        op.execute(sa.schema.DropSequence(sa.Sequence(name, schema=schema)))
    for schema in reversed(SCHEMAS):
        op.execute(f"DROP SCHEMA IF EXISTS {schema} CASCADE")
